package delfinen.presentation;

import delfinen.data.FileDAO;
import delfinen.logic.Status;
import delfinen.logic.CasualSwimmer;
import delfinen.logic.CompetitionSwimmer;
import delfinen.logic.Controller;
import delfinen.logic.Discipline;
import java.util.ArrayList;

/**
 *
 * @author Niklas
 */
public class GUI extends javax.swing.JFrame {

    private Controller c;

    public GUI() {
        c = new Controller(new FileDAO());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupDisciplines = new javax.swing.ButtonGroup();
        jButtonShowSwimmers = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSwimmerOverview = new javax.swing.JTextArea();
        jTextFieldAge = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabelID = new javax.swing.JLabel();
        jButtonGetSwimmer = new javax.swing.JButton();
        jButtonEditSwimmer = new javax.swing.JButton();
        jButtonAddSwimmer = new javax.swing.JButton();
        jRadioButtonCrawl = new javax.swing.JRadioButton();
        jRadioButtonBreast = new javax.swing.JRadioButton();
        jRadioBack = new javax.swing.JRadioButton();
        jRadioButtonButter = new javax.swing.JRadioButton();
        jButtonAddResult = new javax.swing.JButton();
        jTextFieldTime = new javax.swing.JTextField();
        jTextFieldDate = new javax.swing.JTextField();
        jTextFieldComp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelPaid = new javax.swing.JLabel();
        jButtonNotPaid = new javax.swing.JButton();
        jComboBoxTeam = new javax.swing.JComboBox<>();
        jComboBoxPaid = new javax.swing.JComboBox<>();
        jComboBoxStatus = new javax.swing.JComboBox<>();
        jComboBoxDisciplines = new javax.swing.JComboBox<>();
        jComboBoxTop5Disciplines = new javax.swing.JComboBox<>();
        jButtonShowTop5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonRemoveSwimmer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonShowSwimmers.setText("All Swimmers");
        jButtonShowSwimmers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowSwimmersActionPerformed(evt);
            }
        });

        jTextAreaSwimmerOverview.setColumns(20);
        jTextAreaSwimmerOverview.setRows(5);
        jScrollPane1.setViewportView(jTextAreaSwimmerOverview);

        jLabel1.setText("Age");

        jLabel2.setText("Name");

        jLabel3.setText("Status");

        jLabel4.setText("Team");

        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });

        jLabelID.setText("  ID");

        jButtonGetSwimmer.setText("GO");
        jButtonGetSwimmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGetSwimmerActionPerformed(evt);
            }
        });

        jButtonEditSwimmer.setText("Edit ");
        jButtonEditSwimmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditSwimmerActionPerformed(evt);
            }
        });

        jButtonAddSwimmer.setText("Add Swimmer");
        jButtonAddSwimmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddSwimmerActionPerformed(evt);
            }
        });

        jRadioButtonCrawl.setText("Crawl");
        jRadioButtonCrawl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCrawlActionPerformed(evt);
            }
        });

        jRadioButtonBreast.setText("Breast");
        jRadioButtonBreast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonBreastActionPerformed(evt);
            }
        });

        jRadioBack.setText("Back");
        jRadioBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBackActionPerformed(evt);
            }
        });

        jRadioButtonButter.setText("Butterfly");
        jRadioButtonButter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonButterActionPerformed(evt);
            }
        });

        jButtonAddResult.setText("Add Result");
        jButtonAddResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddResultActionPerformed(evt);
            }
        });

        jLabel7.setText("Time");

        jLabel8.setText("Date");

        jLabel9.setText("Competition");

        jLabel10.setText("Discipline");

        jLabelPaid.setText("Paid");

        jButtonNotPaid.setText("Not paid");
        jButtonNotPaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNotPaidActionPerformed(evt);
            }
        });

        jComboBoxTeam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casual", "Junior", "Senior" }));
        jComboBoxTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTeamActionPerformed(evt);
            }
        });

        jComboBoxPaid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));

        jComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"ACTIVE","PASSIVE" }));

        jComboBoxDisciplines.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Crawl", "Backstroke", "Breaststroke", "Butterfly" }));
        jComboBoxDisciplines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDisciplinesActionPerformed(evt);
            }
        });

        jComboBoxTop5Disciplines.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Crawl", "Backstroke", "Breaststroke", "Butterfly" }));
        jComboBoxTop5Disciplines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTop5DisciplinesActionPerformed(evt);
            }
        });

        jButtonShowTop5.setText("GO");
        jButtonShowTop5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowTop5ActionPerformed(evt);
            }
        });

        jLabel5.setText("Top5");

        jLabel6.setText("Edit");

        jButtonRemoveSwimmer.setText("Remove");
        jButtonRemoveSwimmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveSwimmerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddResult)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldTime, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldComp, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBoxDisciplines, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jComboBoxTop5Disciplines, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButtonShowTop5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonRemoveSwimmer)
                                            .addGap(77, 77, 77)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButtonGetSwimmer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonEditSwimmer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonCrawl)
                            .addComponent(jRadioBack)
                            .addComponent(jRadioButtonBreast)
                            .addComponent(jRadioButtonButter))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonNotPaid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonShowSwimmers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(278, 278, 278)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jButtonAddSwimmer)
                    .addComponent(jLabelPaid)
                    .addComponent(jComboBoxPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAddResult)
                            .addComponent(jButtonAddSwimmer)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxTop5Disciplines, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonShowTop5))
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(60, 60, 60)
                                .addComponent(jButtonRemoveSwimmer))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jButtonEditSwimmer))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jButtonGetSwimmer))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(4, 4, 4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxDisciplines, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addComponent(jButtonShowSwimmers)
                        .addGap(10, 10, 10)
                        .addComponent(jButtonNotPaid))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)
                        .addGap(15, 15, 15)
                        .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabelPaid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxPaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jRadioButtonCrawl)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonButter)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonBreast)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioBack)
                        .addGap(91, 91, 91)))
                .addGap(2, 2, 2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonShowSwimmersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowSwimmersActionPerformed
        jTextAreaSwimmerOverview.setText(c.getAllSwimmers());
        if (c.getAllSwimmers().isEmpty()) {
            jTextAreaSwimmerOverview.setText("There is no swimmers");
        }
    }//GEN-LAST:event_jButtonShowSwimmersActionPerformed

    private void jButtonGetSwimmerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGetSwimmerActionPerformed
        for (CasualSwimmer swimmer : c.swimmersFromFile()) {
            if (swimmer.getId() == Integer.parseInt(jTextFieldID.getText())) {
                jTextFieldAge.setText(Integer.toString(swimmer.getAge()));
                jTextFieldName.setText(swimmer.getName());

                if (swimmer.getStatus().toString().equalsIgnoreCase("Active")) {
                    jComboBoxStatus.setSelectedIndex(0);
                }
                if (swimmer.getStatus().toString().equalsIgnoreCase("Passive")) {
                    jComboBoxStatus.setSelectedIndex(1);
                }

                if (swimmer.getTeam().equalsIgnoreCase("Casual")) {
                    jComboBoxTeam.setSelectedIndex(0);
                }
                if (swimmer.getTeam().equalsIgnoreCase("Junior")) {
                    jComboBoxTeam.setSelectedIndex(1);
                }
                if (swimmer.getTeam().equalsIgnoreCase("Senior")) {
                    jComboBoxTeam.setSelectedIndex(2);
                }

                if (swimmer.isPaid()) {
                    jComboBoxPaid.setSelectedIndex(0);
                }
                if (!swimmer.isPaid()) {
                    jComboBoxPaid.setSelectedIndex(1);
                }
            }
        }
    }//GEN-LAST:event_jButtonGetSwimmerActionPerformed

    private void jButtonEditSwimmerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditSwimmerActionPerformed
        boolean paid = false;
        int id = Integer.parseInt(jTextFieldID.getText());
        int age = Integer.parseInt(jTextFieldAge.getText());
        String name = jTextFieldName.getText();
        String status = (String) this.jComboBoxStatus.getSelectedItem();
        String upperStatus = status.toUpperCase();
        String team = (String) this.jComboBoxTeam.getSelectedItem();
        if (jComboBoxPaid.getSelectedItem().equals("Yes")) {
            paid = true;
        }
        if (jComboBoxPaid.getSelectedItem().equals("No")) {
            paid = false;
        }

        c.editSwimmer(id, age, name, Status.valueOf(upperStatus), team, paid);

        jTextFieldID.setText("");
        jTextFieldName.setText("");
        jTextFieldAge.setText("");

    }//GEN-LAST:event_jButtonEditSwimmerActionPerformed

    private void jButtonAddSwimmerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddSwimmerActionPerformed
        ArrayList<Discipline> disciplines = new ArrayList<>();
        CompetitionSwimmer compSwimmer;
        boolean paid = false;
        int age = Integer.parseInt(jTextFieldAge.getText());
        String name = jTextFieldName.getText();
        String status = (String) this.jComboBoxStatus.getSelectedItem();
        String upperStatus = status.toUpperCase();
        String team = (String) this.jComboBoxTeam.getSelectedItem();
        if (jComboBoxPaid.getSelectedItem().equals("Yes")) {
            paid = true;
        }
        if (jComboBoxPaid.getSelectedItem().equals("No")) {
            paid = false;
        }
        if (this.jComboBoxTeam.getSelectedIndex() == 0) {
            c.newCasualSwimmer(age, name, Status.valueOf(upperStatus), team, paid);
        } else {
            compSwimmer = c.newCompSwimmer(age, name, Status.valueOf(upperStatus), team, paid);
            if (jRadioButtonBreast.isSelected()) {
                disciplines.add(Discipline.BREASTSTROKE);
            }
            if (jRadioBack.isSelected()) {
                disciplines.add(Discipline.BACKSTROKE);
            }
            if (jRadioButtonCrawl.isSelected()) {
                disciplines.add(Discipline.CRAWL);
            }
            if (jRadioButtonButter.isSelected()) {
                disciplines.add(Discipline.BUTTERFLY);
            }
            c.addDisciplines(disciplines, compSwimmer);

    }//GEN-LAST:event_jButtonAddSwimmerActionPerformed
        jTextFieldName.setText("");
        jTextFieldAge.setText("");
    }

    private void jRadioButtonCrawlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCrawlActionPerformed

    }//GEN-LAST:event_jRadioButtonCrawlActionPerformed

    private void jRadioButtonBreastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonBreastActionPerformed

    }//GEN-LAST:event_jRadioButtonBreastActionPerformed

    private void jRadioBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBackActionPerformed

    }//GEN-LAST:event_jRadioBackActionPerformed

    private void jRadioButtonButterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonButterActionPerformed

    }//GEN-LAST:event_jRadioButtonButterActionPerformed

    private void jButtonAddResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddResultActionPerformed
        Discipline discipline = null;
        String competition = jTextFieldComp.getText();
        int id = Integer.parseInt(jTextFieldID.getText());
        double time = Double.parseDouble(jTextFieldTime.getText());
        double date = Double.parseDouble(jTextFieldDate.getText());
        int i = jComboBoxDisciplines.getSelectedIndex();
        switch (i) {
            case 0:
                discipline = Discipline.CRAWL;
                break;
            case 1:
                discipline = Discipline.BACKSTROKE;
                break;
            case 2:
                discipline = Discipline.BREASTSTROKE;
                break;
            case 3:
                discipline = Discipline.BUTTERFLY;

        }
        c.newResult(id, discipline, time, date, competition);
        c.addResult(id, discipline, time);
    }//GEN-LAST:event_jButtonAddResultActionPerformed

    private void jButtonNotPaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNotPaidActionPerformed
        jTextAreaSwimmerOverview.setText("");
        jTextAreaSwimmerOverview.setText(c.swimmersNotPaid());
    }//GEN-LAST:event_jButtonNotPaidActionPerformed

    private void jComboBoxTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTeamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTeamActionPerformed

    private void jComboBoxDisciplinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDisciplinesActionPerformed


    }//GEN-LAST:event_jComboBoxDisciplinesActionPerformed

    private void jComboBoxTop5DisciplinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTop5DisciplinesActionPerformed

    }//GEN-LAST:event_jComboBoxTop5DisciplinesActionPerformed

    private void jButtonShowTop5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowTop5ActionPerformed
        if (jComboBoxTop5Disciplines.getSelectedIndex() == 0) {
            jTextAreaSwimmerOverview.setText(c.getTop5(Discipline.CRAWL));
            if (c.getTop5(Discipline.CRAWL).isEmpty()) {
                jTextAreaSwimmerOverview.setText("No results yet");
            }

        }
        if (jComboBoxTop5Disciplines.getSelectedIndex() == 1) {
            jTextAreaSwimmerOverview.setText(c.getTop5(Discipline.BACKSTROKE));
        }
        if (jComboBoxTop5Disciplines.getSelectedIndex() == 2) {
            jTextAreaSwimmerOverview.setText(c.getTop5(Discipline.BREASTSTROKE));
        }
        if (jComboBoxTop5Disciplines.getSelectedIndex() == 3) {
            jTextAreaSwimmerOverview.setText(c.getTop5(Discipline.BUTTERFLY));
        }
    }//GEN-LAST:event_jButtonShowTop5ActionPerformed

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void jButtonRemoveSwimmerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveSwimmerActionPerformed
        int id = Integer.parseInt(jTextFieldID.getText());
        c.removeSwimmer(id);
    }//GEN-LAST:event_jButtonRemoveSwimmerActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupDisciplines;
    private javax.swing.JButton jButtonAddResult;
    private javax.swing.JButton jButtonAddSwimmer;
    private javax.swing.JButton jButtonEditSwimmer;
    private javax.swing.JButton jButtonGetSwimmer;
    private javax.swing.JButton jButtonNotPaid;
    private javax.swing.JButton jButtonRemoveSwimmer;
    private javax.swing.JButton jButtonShowSwimmers;
    private javax.swing.JButton jButtonShowTop5;
    private javax.swing.JComboBox<String> jComboBoxDisciplines;
    private javax.swing.JComboBox<String> jComboBoxPaid;
    private javax.swing.JComboBox<String> jComboBoxStatus;
    private javax.swing.JComboBox<String> jComboBoxTeam;
    private javax.swing.JComboBox<String> jComboBoxTop5Disciplines;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelPaid;
    private javax.swing.JRadioButton jRadioBack;
    private javax.swing.JRadioButton jRadioButtonBreast;
    private javax.swing.JRadioButton jRadioButtonButter;
    private javax.swing.JRadioButton jRadioButtonCrawl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaSwimmerOverview;
    private javax.swing.JTextField jTextFieldAge;
    private javax.swing.JTextField jTextFieldComp;
    private javax.swing.JTextField jTextFieldDate;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldTime;
    // End of variables declaration//GEN-END:variables
}
